version: '3'

services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: javaSpringEmailDb
      MYSQL_USER: user
      MYSQL_PASSWORD: password

    ports:
      - "3306:3306"
    command: ""

  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    links:
      - db

